### ISSUE TITLE
Rename the `closureOption` argument in ImpactedClassesMojo

### ISSUE THREAD

**Issue by ayakayorihiro** [SoftEngResearch/emop#68]
We currently have the options

-      TRANSITIVE_OF_INVERSE_TRANSITIVE = p1
-      TRANSITIVE_AND_INVERSE_TRANSITIVE = p2
-      TRANSITIVE = p3

, but we should rename to be PS1, PS2, PS3.

**Comment by owolabileg** [comment]
To be clear, these current option names are unintuitive and I never know what maps to which variant. So, renaming as @ayakayorihiro writes will help us and our users in the future.
